import { DayWorkout } from "../types";

const pexels = (id: string) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1200`;

const IMG = {
  benchPress: pexels("3837781"),
  inclinePress: pexels("34651540"),
  cableFly: pexels("7289250"),
  ropePushdown: pexels("6243176"),
  overheadExtension: pexels("13616289"),
  dips: pexels("4803875"),
  latPulldown: pexels("18060085"),
  seatedRow: pexels("4162482"),
  dbRow: pexels("34043599"),
  barbellCurl: pexels("9073246"),
  inclineDbCurl: pexels("29526383"),
  hammerCurl: pexels("6455960"),
  squat: pexels("1552106"),
  legCurl: pexels("28731788"),
  legExtension: pexels("19722966"),
  calfRaise: pexels("13965339"),
  hangingLegRaise: pexels("4803688"),
  cableCrunch: pexels("4720528"),
  shoulderPress: pexels("7289367"),
  lateralRaise: pexels("29793977"),
  rearDeltFly: pexels("29865137"),
  skullCrusher: pexels("5496589"),
  lunges: pexels("6339676"),
  plank: pexels("6285204"),
  russianTwist: pexels("5128466"),
};

export const WORKOUT_DATA: DayWorkout[] = [
  {
    day: "Monday",
    muscle: "Chest + Triceps",
    exercises: [
      {
        id: "1",
        name: "Bench Press",
        sets: 4,
        reps: "8-10",
        image: IMG.benchPress,
        description: "Barbell chest press.",
      },
      {
        id: "2",
        name: "Incline DB Press",
        sets: 3,
        reps: "10-12",
        image: IMG.inclinePress,
        description: "Incline dumbbell chest press.",
      },
      {
        id: "3",
        name: "Cable / DB Fly",
        sets: 3,
        reps: "12-15",
        image: IMG.cableFly,
        description: "Controlled chest fly movement.",
      },
      {
        id: "4",
        name: "Rope Pushdown",
        sets: 3,
        reps: "12-15",
        image: IMG.ropePushdown,
        description: "Cable rope triceps pushdown.",
      },
      {
        id: "5",
        name: "Overhead DB Extension",
        sets: 3,
        reps: "10-12",
        image: IMG.overheadExtension,
        description: "Overhead dumbbell triceps extension.",
      },
      {
        id: "6",
        name: "Dips",
        sets: 2,
        reps: "Failure",
        image: IMG.dips,
        description: "Bodyweight dips to failure.",
      },
    ],
  },
  {
    day: "Tuesday",
    muscle: "Back + Biceps",
    exercises: [
      {
        id: "7",
        name: "Lat Pulldown / Pull-ups",
        sets: 4,
        reps: "10-12",
        image: IMG.latPulldown,
        description: "Vertical pulling movement.",
      },
      {
        id: "8",
        name: "Seated Cable Row",
        sets: 3,
        reps: "10-12",
        image: IMG.seatedRow,
        description: "Horizontal cable rowing.",
      },
      {
        id: "9",
        name: "One Arm DB Row",
        sets: 3,
        reps: "12",
        image: IMG.dbRow,
        description: "Single-arm dumbbell rowing.",
      },
      {
        id: "10",
        name: "Barbell Curl",
        sets: 3,
        reps: "10-12",
        image: IMG.barbellCurl,
        description: "Standing barbell biceps curl.",
      },
      {
        id: "11",
        name: "Incline DB Curl",
        sets: 3,
        reps: "12",
        image: IMG.inclineDbCurl,
        description: "Incline bench dumbbell curl.",
      },
      {
        id: "12",
        name: "Hammer Curl",
        sets: 2,
        reps: "12-15",
        image: IMG.hammerCurl,
        description: "Neutral-grip dumbbell curl.",
      },
    ],
  },
  {
    day: "Wednesday",
    muscle: "Legs + Abs",
    exercises: [
      {
        id: "13",
        name: "Squats / Leg Press",
        sets: 4,
        reps: "8-10",
        image: IMG.squat,
        description: "Primary lower-body compound lift.",
      },
      {
        id: "14",
        name: "Leg Curl",
        sets: 3,
        reps: "12",
        image: IMG.legCurl,
        description: "Hamstring isolation movement.",
      },
      {
        id: "15",
        name: "Leg Extension",
        sets: 3,
        reps: "12",
        image: IMG.legExtension,
        description: "Quadriceps isolation movement.",
      },
      {
        id: "16",
        name: "Standing Calf Raises",
        sets: 4,
        reps: "15-20",
        image: IMG.calfRaise,
        description: "Standing calf raises.",
      },
      {
        id: "17",
        name: "Hanging Leg Raise",
        sets: 3,
        reps: "12",
        image: IMG.hangingLegRaise,
        description: "Hanging core raise.",
      },
      {
        id: "18",
        name: "Cable Crunch",
        sets: 3,
        reps: "15",
        image: IMG.cableCrunch,
        description: "Weighted cable crunch.",
      },
    ],
  },
  {
    day: "Thursday",
    muscle: "Chest + Shoulders",
    exercises: [
      {
        id: "19",
        name: "Incline Bench Press",
        sets: 4,
        reps: "8-10",
        image: IMG.inclinePress,
        description: "Incline barbell chest press.",
      },
      {
        id: "20",
        name: "Flat DB Press",
        sets: 3,
        reps: "10-12",
        image: IMG.benchPress,
        description: "Flat dumbbell chest press.",
      },
      {
        id: "21",
        name: "DB Shoulder Press",
        sets: 3,
        reps: "10",
        image: IMG.shoulderPress,
        description: "Overhead dumbbell shoulder press.",
      },
      {
        id: "22",
        name: "Lateral Raises",
        sets: 4,
        reps: "12-15",
        image: IMG.lateralRaise,
        description: "Side-delt isolation raise.",
      },
      {
        id: "23",
        name: "Rear Delt Fly",
        sets: 3,
        reps: "15",
        image: IMG.rearDeltFly,
        description: "Rear-delt focused fly.",
      },
    ],
  },
  {
    day: "Friday",
    muscle: "Back + Arms",
    exercises: [
      {
        id: "24",
        name: "Wide Grip Lat Pulldown",
        sets: 4,
        reps: "10-12",
        image: IMG.latPulldown,
        description: "Wide-grip vertical pull.",
      },
      {
        id: "25",
        name: "Chest Supported Row / Machine Row",
        sets: 3,
        reps: "10-12",
        image: IMG.seatedRow,
        description: "Chest-supported horizontal row.",
      },
      {
        id: "26",
        name: "EZ Bar Curl",
        sets: 3,
        reps: "10",
        image: IMG.barbellCurl,
        description: "EZ-bar biceps curl.",
      },
      {
        id: "27",
        name: "Skull Crushers",
        sets: 3,
        reps: "10-12",
        image: IMG.skullCrusher,
        description: "Lying triceps extension.",
      },
      {
        id: "28",
        name: "Rope Hammer Curl",
        sets: 2,
        reps: "12",
        image: IMG.hammerCurl,
        description: "Cable rope hammer curl.",
      },
      {
        id: "29",
        name: "Rope Pushdown",
        sets: 2,
        reps: "12",
        image: IMG.ropePushdown,
        description: "Cable rope triceps pushdown.",
      },
    ],
  },
  {
    day: "Saturday",
    muscle: "Legs + Abs",
    exercises: [
      {
        id: "30",
        name: "Hack Squat / Goblet Squat",
        sets: 4,
        reps: "10",
        image: IMG.squat,
        description: "Squat variation as planned.",
      },
      {
        id: "31",
        name: "Leg Extension",
        sets: 3,
        reps: "12-15",
        image: IMG.legExtension,
        description: "Quadriceps isolation movement.",
      },
      {
        id: "32",
        name: "Leg Curls",
        sets: 3,
        reps: "12-15",
        image: IMG.legCurl,
        description: "Hamstring isolation movement.",
      },
      {
        id: "33",
        name: "Walking Lunges",
        sets: 3,
        reps: "12",
        image: IMG.lunges,
        description: "Walking lunge steps.",
      },
      {
        id: "34",
        name: "Seated Calf Raises",
        sets: 4,
        reps: "15-20",
        image: IMG.calfRaise,
        description: "Seated calf raise movement.",
      },
      {
        id: "35",
        name: "Plank",
        sets: 3,
        reps: "45-60 sec",
        image: IMG.plank,
        description: "Core plank hold.",
      },
      {
        id: "36",
        name: "Russian Twist",
        sets: 3,
        reps: "20",
        image: IMG.russianTwist,
        description: "Alternating oblique twists.",
      },
    ],
  },
];

export const DAYS = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const getWorkoutByDay = (day: string): DayWorkout | undefined => {
  return WORKOUT_DATA.find((w) => w.day === day);
};
